GC_TYPES = ["s", "mc"]
DEFAULT_LIMIT = 100
DEFAULT_PAGE = 1
ANOMALY_THRESHOLDS = {
    "high_cpu_percent": 80.0,      # system CPU percent
    "pause_minor_ms": 100.0,       # minor GC long pause threshold
    "pause_major_ms": 1000.0,      # major GC long pause threshold
    "promotion_ratio": 80.0,       # %
    "low_memory_ratio": 0.10,      # mem_available/mem_total
}
CRITICALITY_THRESHOLDS = {
    # Leak detection
    "leak_slope_warn_mb_per_min": 2.0,
    "leak_slope_crit_mb_per_min": 5.0,
    "leak_r2_min": 0.3,
    # GC pause percentiles (p95)
    "gc_p95_minor_warn": 100.0,
    "gc_p95_minor_crit": 200.0,
    "gc_p95_major_warn": 500.0,
    "gc_p95_major_crit": 1000.0,
    # Ratios
    "high_cpu_ratio_crit": 0.5,
}
EMPTY_COLS_IN_SYSTEM_METRICS = ['allocated',
'average_survival_ratio',
'background_evacuate_copy',
'background_evacuate_update_pointers',
'background_mark',
'background_scavenge_parallel',
'background_sweep',
'clear',
'clear_dependent_code',
'clear_external_string_table',
'clear_join_job',
'clear_maps',
'clear_slots_buffer',
'clear_string_forwarding_table',
'clear_weak_collections',
'clear_weak_global_handles',
'clear_weak_lists',
'clear_weak_references',
'compaction_speed',
'complete_sweep_array_buffers',
'complete_sweeping',
'conservative_stack_scanning',
'epilogue',
'evacuate',
'evacuate_candidates',
'evacuate_clean_up',
'evacuate_copy',
'evacuate_epilogue',
'evacuate_prologue',
'evacuate_rebalance',
'evacuate_update_pointers',
'evacuate_update_pointers_slots_main',
'evacuate_update_pointers_to_new_roots',
'evacuate_update_pointers_weak',
'execution_phase',
'finish',
'finish_sweep_array_buffers',
'gc_type',
'heap_embedder_tracing_epilogue',
'heap_epilogue',
'heap_epilogue_reduce_new_space',
'heap_external_epilogue',
'heap_external_prologue',
'heap_external_weak_global_handles',
'heap_prologue',
'holes_size_after',
'holes_size_before',
'incremental',
'incremental_embedder_tracing',
'incremental_finalize',
'incremental_finalize_external_epilogue',
'incremental_finalize_external_prologue',
'incremental_layout_change',
'incremental_longest_step',
'incremental_marking_throughput',
'incremental_steps_count',
'incremental_steps_took',
'incremental_sweep_array_buffers',
'incremental_sweeping',
'incremental_walltime_duration',
'incremental_wrapper_tracing_longest_step',
'interleaved',
'mark',
'mark_embedder_prologue',
'mark_embedder_tracing',
'mark_ephemeron_linear',
'mark_ephemeron_marking',
'mark_finish_incremental',
'mark_full_closure',
'mark_full_closure_parallel',
'mark_roots',
'mutator_ms',
'new_space_allocation_throughput',
'new_space_survive_rate',
'new_space_survive_rate_',
'new_space_survived',
'nodes_copied_in_new',
'nodes_died_in_new',
'nodes_promoted',
'pause_ms',
'pid',
'pool_chunks',
'prologue',
'promoted',
'promotion_rate',
'promotion_ratio',
'reduce_memory',
'scavenge',
'scavenge_free_remembered_set',
'scavenge_parallel',
'scavenge_roots',
'scavenge_sweep_array_buffers',
'scavenge_throughput',
'scavenge_update_refs',
'scavenge_weak',
'scavenge_weak_global_handles_identify',
'scavenge_weak_global_handles_process',
'sweep',
'sweep_code',
'sweep_map',
'sweep_new',
'sweep_new_lo',
'sweep_old',
'sweep_start_jobs',
'time_to_safepoint',
'total_size_after',
'total_size_before',
'verbose_all_spaces_avail_kb',
'verbose_all_spaces_committed_kb',
'verbose_all_spaces_used_kb',
'verbose_backing_store_memory_kb',
'verbose_code_large_object_space_avail_kb',
'verbose_code_large_object_space_committed_kb',
'verbose_code_large_object_space_used_kb',
'verbose_code_space_avail_kb',
'verbose_code_space_committed_kb',
'verbose_code_space_used_kb',
'verbose_external_memory_global_kb',
'verbose_external_memory_reported_kb',
'verbose_large_object_space_avail_kb',
'verbose_large_object_space_committed_kb',
'verbose_large_object_space_used_kb',
'verbose_mem_alloc_avail_kb',
'verbose_mem_alloc_used_kb',
'verbose_new_large_object_space_avail_kb',
'verbose_new_large_object_space_committed_kb',
'verbose_new_large_object_space_used_kb',
'verbose_new_space_avail_kb',
'verbose_new_space_committed_kb',
'verbose_new_space_used_kb',
'verbose_old_space_avail_kb',
'verbose_old_space_committed_kb',
'verbose_old_space_used_kb',
'verbose_pool_chunks',
'verbose_pool_committed_kb',
'verbose_read_only_space_avail_kb',
'verbose_read_only_space_committed_kb',
'verbose_read_only_space_used_kb',
'verbose_total_gc_time_ms',
'verbose_trusted_large_object_space_avail_kb',
'verbose_trusted_large_object_space_committed_kb',
'verbose_trusted_large_object_space_used_kb',
'verbose_trusted_space_avail_kb',
'verbose_trusted_space_committed_kb',
'verbose_trusted_space_used_kb'
]


EMPTY_COLS_IN_GC_EVENTS = [
'buffers_kib',
'cached_kib',
'cgroup_cache_bytes',
'cgroup_cpu_system_delta_usec',
'cgroup_cpu_system_pct',
'cgroup_cpu_system_usec',
'cgroup_cpu_usage_delta_usec',
'cgroup_cpu_usage_usec',
'cgroup_cpu_user_delta_usec',
'cgroup_cpu_user_pct',
'cgroup_cpu_user_usec',
'cgroup_cpu_utilization_pct',
'cgroup_limit_bytes',
'cgroup_usage_bytes',
'cpu_idle',
'cpu_iowait',
'cpu_irq',
'cpu_nice',
'cpu_softirq',
'cpu_steal',
'cpu_system',
'cpu_user',
'cpu_user_nice_sys_idle_iowait_irq_softirq_steal_semicolon',
'ctxt_switches',
'interrupts',
'interval_usec',
'load_avg_15min',
'load_avg_1_5_15_semicolon',
'load_avg_1min',
'load_avg_5min',
'mem_available_kib',
'mem_free_kib',
'mem_total_kib',
'monitored_node_pid',
'node_cpus_allowed',
'node_ctxt_nonvoluntary',
'node_ctxt_voluntary',
'node_data_kib',
'node_exe_kib',
'node_fds',
'node_fdsize',
'node_hwm_kib',
'node_lck_kib',
'node_lib_kib',
'node_mems_allowed',
'node_peak_kib',
'node_pte_kib',
'node_rss_anon_kib',
'node_rss_file_kib',
'node_rss_kib',
'node_rss_shmem_kib',
'node_size_kib',
'node_state',
'node_stk_kib',
'node_swap_kib',
'node_tgid',
'node_threads',
'process_time_ms',
'wall_time'
]

ANOMALY_THRESHOLDS = {
    "pause_minor_ms": 100.0,      # > 100ms for minor GC is bad
    "pause_major_ms": 1000.0,     # > 1000ms for major GC is bad
    "promotion_ratio": 80.0,      # > 80% promotion is high pressure
    "low_memory_ratio": 0.10,     # < 10% available memory is low
    "high_cpu_percent": 80.0,
}
